# Render Blueprint for HealthIQ Backend
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: healthiq-backend
    runtime: python
    region: oregon
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: gunicorn healthiq.wsgi:application --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        value: h2343s78byucri@8sdfh23u4y2u3h4
      - key: DEBUG
        value: "False"
      - key: MONGO_URI
        value: mongodb+srv://lokeshca2004_db_user:2NCTdCoJtfuUPkA2@cluster0.rbf0jwg.mongodb.net/
      - key: MONGODB_NAME
        value: health_monitor
      - key: FRONTEND_URL
        value: https://health-compass-rose.vercel.app
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: SECURE_SSL_REDIRECT
        value: "False"
